### ISSUE TITLE
Collecting ideas for Logo

### ISSUE THREAD

**Issue by tulasinandan** [PlasmaPy/PlasmaPy#90] opened 2017-08-22 18:44 UTC
1) Snakes reconnecting!
2) Tokamak/Stellerator around the Sun
3) Lots of other snake ideas: Snake following particle path aroung B, B going around snake, ...

**Comment by namurphy** [comment] 2017-08-22 19:18
@tulasinandan - I forgot to mention on the telecon that there is an issue already for the logo.  Could you add these thoughts to https://github.com/PlasmaPy/PlasmaPy/issues/71?  Thank you!

**Comment by StanczakDominik** [comment] 2017-08-25 03:36
Duplicate of #71. So we don't have to remember to close this.

**Closed** 2017-08-30 18:06 UTC
Labels: Duplicate
